version: '3.5'
services:
  postgres:
    container_name: pg0
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres
    ports:
      - "5432:5432"
    restart: unless-stopped