spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/template"
    username: "postgres"
    password: "postgres"
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        format_sql: true